% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Hw06ST430Yu},
  pdfauthor={Haozhe (Jerry) Yu},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Hw06ST430Yu}
\author{Haozhe (Jerry) Yu}
\date{2023-11-10}

\begin{document}
\maketitle

\hypertarget{question-1}{%
\section{Question 1}\label{question-1}}

A researcher studied the effects of the charge rate and temperature on
the life of a new type of power cell in a preliminary small-scale
experiment. The charge rate (Xl) was controlled at three levels (0.6,
1.0, and 1.4 amperes) and the ambient temperature (X2) was controlled at
three levels (l0, 20, 30°C). Factors pertaining to the discharge of the
power cell were held at fixed levels. The life of the power cell (Y) was
measured in terms of the number of discharge-charge cycles that a power
cell underwent before it failed.

The researcher was not sure about the nature of the response function in
the range of the factors studied. Hence, the researcher decided to fit
the second-order polynomial regression model

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"Datasets/battery.txt"}\NormalTok{, }\AttributeTok{header=}\ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{names}\NormalTok{(data) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"cycles"}\NormalTok{,}\StringTok{"rate"}\NormalTok{,}\StringTok{"temp"}\NormalTok{)}
\FunctionTok{attach}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\#\#a. Find the correlation matrix and report any high correlation
between predictor variables.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            cycles       rate      temp
## cycles  1.0000000 -0.5555349 0.7512159
## rate   -0.5555349  1.0000000 0.0000000
## temp    0.7512159  0.0000000 1.0000000
\end{verbatim}

The correlation between cycles and temp is 0.7512159. This is high and
could be a sign of multicollinearity.

\#\#b. Fit a full model (Shown above) and report the overall F value and
individual t-values. Do you suspect any multicollinearity problem?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod1}\OtherTok{\textless{}{-}}\FunctionTok{lm}\NormalTok{(cycles}\SpecialCharTok{\textasciitilde{}}\NormalTok{rate}\SpecialCharTok{+}\NormalTok{temp}\SpecialCharTok{+}\FunctionTok{I}\NormalTok{(rate}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{+}\FunctionTok{I}\NormalTok{(temp}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(rate}\SpecialCharTok{*}\NormalTok{temp))}
\FunctionTok{summary}\NormalTok{(mod1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = cycles ~ rate + temp + I(rate^2) + I(temp^2) + I(rate * 
##     temp))
## 
## Residuals:
##       1       2       3       4       5       6       7       8       9      10 
## -21.465   9.263  12.202  41.930  -5.842 -31.842  21.158 -25.404 -20.465   7.263 
##      11 
##  13.202 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(>|t|)  
## (Intercept)     337.7215   149.9616   2.252   0.0741 .
## rate           -539.5175   268.8603  -2.007   0.1011  
## temp              8.9171     9.1825   0.971   0.3761  
## I(rate^2)       171.2171   127.1255   1.347   0.2359  
## I(temp^2)        -0.1061     0.2034  -0.521   0.6244  
## I(rate * temp)    2.8750     4.0468   0.710   0.5092  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 32.37 on 5 degrees of freedom
## Multiple R-squared:  0.9135, Adjusted R-squared:  0.8271 
## F-statistic: 10.57 on 5 and 5 DF,  p-value: 0.01086
\end{verbatim}

Yes I do. The overall p value for the ANOVA is \textless{} 0.05, but
each of the individual regression coefficient's p values are more than
0.05. This is a sign of multicollinearity. Additionaly, this is a
polynomial regression that has not been centered so by definition it
will have structural multicollinearity.

\hypertarget{c.-we-can-remove-the-high-correlation-between-explanatory-variables-and-their-powers-by-centering.}{%
\subsection{c.~We can remove the high correlation between explanatory
variables and their powers by
centering.}\label{c.-we-can-remove-the-high-correlation-between-explanatory-variables-and-their-powers-by-centering.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rate.code }\OtherTok{\textless{}{-}}\NormalTok{ (rate}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(rate))}\SpecialCharTok{/}\FloatTok{0.4}
\NormalTok{temp.code }\OtherTok{\textless{}{-}}\NormalTok{ (temp}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(temp))}\SpecialCharTok{/}\DecValTok{10}
\FunctionTok{cor}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(rate.code,temp.code,rate.code}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{,temp.code}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               rate.code temp.code                            
## rate.code  1.000000e+00         0 -4.042173e-16 -1.994753e-17
## temp.code  0.000000e+00         1  0.000000e+00  0.000000e+00
##           -4.042173e-16         0  1.000000e+00  2.666667e-01
##           -1.994753e-17         0  2.666667e-01  1.000000e+00
\end{verbatim}

In this new correlation matrix I do not obervs any high correlations and
therefore signs of multicollinearity.

\hypertarget{d.fit-a-new-full-model-with-the-scaled-new-predictor-variables-and-report-the-estimated-regression-function}{%
\subsection{d.Fit a new full model with the scaled new predictor
variables and report the estimated regression
function}\label{d.fit-a-new-full-model-with-the-scaled-new-predictor-variables-and-report-the-estimated-regression-function}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod2}\OtherTok{\textless{}{-}}\FunctionTok{lm}\NormalTok{(cycles}\SpecialCharTok{\textasciitilde{}}\NormalTok{rate.code}\SpecialCharTok{+}\NormalTok{temp.code}\SpecialCharTok{+}\FunctionTok{I}\NormalTok{(rate.code}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{+}\FunctionTok{I}\NormalTok{(temp.code}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{+}\FunctionTok{I}\NormalTok{(rate.code}\SpecialCharTok{*}\NormalTok{temp.code))}
\FunctionTok{summary}\NormalTok{(mod2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = cycles ~ rate.code + temp.code + I(rate.code^2) + 
##     I(temp.code^2) + I(rate.code * temp.code))
## 
## Residuals:
##       1       2       3       4       5       6       7       8       9      10 
## -21.465   9.263  12.202  41.930  -5.842 -31.842  21.158 -25.404 -20.465   7.263 
##      11 
##  13.202 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                162.84      16.61   9.805 0.000188 ***
## rate.code                  -55.83      13.22  -4.224 0.008292 ** 
## temp.code                   75.50      13.22   5.712 0.002297 ** 
## I(rate.code^2)              27.39      20.34   1.347 0.235856    
## I(temp.code^2)             -10.61      20.34  -0.521 0.624352    
## I(rate.code * temp.code)    11.50      16.19   0.710 0.509184    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 32.37 on 5 degrees of freedom
## Multiple R-squared:  0.9135, Adjusted R-squared:  0.8271 
## F-statistic: 10.57 on 5 and 5 DF,  p-value: 0.01086
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(mod2)}\SpecialCharTok{$}\NormalTok{coeff[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 162.8421
\end{verbatim}

Cycles = 162.8421053 + -55.8333333rate.code + 75.5temp.code +
27.3947368rate.code\^{}2 + -10.6052632temp.code\^{}2 + 11.5{[}rate.code
* temp.code{]}

\end{document}
